import type { Metadata } from "next";

import Header from '@/components/shared/Header';
import Footer from '@/components/shared/Footer';
import SideBar from "@/components/shared/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="flex">
          <SideBar />
          <div>{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
